#! /usr/bin/env bash
export cmd="docker run -it --env=DISPLAY  
--volume=/tmp/.X11-unix:/tmp/.X11-unix:rw 
--device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie ros_foxy:0.0.2" 
gnome-terminal --window-with-profile="orange" -- bash -c "$cmd ;exec bash"

