services:

###########################################
## Record from sensor and publish to DDS ##
###########################################

    recorder-app:
        build: 
            context: .
            dockerfile: dds_recorder.dockerfile
            args:
                XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
                ROS2_WS: /opt/ros2_ws 
                ROS_DISTRO: foxy

        platform: linux/arm64/v8
        
        stdin_open: true     #docker run -i
        tty: true            #docker run -t
             
##  PulseAudio access with UNIX Socket
##  https://hub.docker.com/r/kyokuheki/vmware-horizon-client  

##  Unix sockets on docker compose
##  https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/ 
        
        environment:
            - DISPLAY
            - XDG_RUNTIME_DIR
        
        networks:
            # - mcm-net
            mcm-net:
                ipv4_address: 172.16.238.9

        command: 
            - /bin/bash
            - -c 
            - |
                echo "Starting the recording service"
                echo "source foxy global setup.bash"
                source "/opt/ros/foxy/setup.bash"
                echo "source "/opt/ros2_ws/src/audio_common/install/local_setup.bash""
                source "/opt/ros2_ws/src/audio_common/install/local_setup.bash"
                
                echo "running audio capture"
                ros2 run audio_capture audio_capture_node
            
        volumes:
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native                   #unix socket
            - ~/.config/pulse/cookie:/root/.config/pulse/cookie
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        devices:
            - /dev/snd
             

networks:
    mcm-net:
        name: mcm-net
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
   
           