services:

###########################################
## Record from sensor and publish to DDS ##
###########################################

    recorder-app:
        build: 
            context: .
            dockerfile: foxy_audio.dockerfile
            args:
                XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
                ROS2_WS: /opt/ros2_ws 
                ROS_DISTRO: foxy

        stdin_open: true     #docker run -i
        tty: true            #docker run -t
             
##  PulseAudio access with UNIX Socket
##  https://hub.docker.com/r/kyokuheki/vmware-horizon-client  

##  Unix sockets on docker compose
##  https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/ 
        
        environment:
            - DISPLAY
            - XDG_RUNTIME_DIR
            
        command: 
            - /bin/bash
            - -c 
            - |
                echo "Starting the recording service"
                echo "source foxy global setup.bash"
                source "/opt/ros/foxy/setup.bash"
                echo "source "/opt/ros2_ws/src/audio_common/install/local_setup.bash""
                source "/opt/ros2_ws/src/audio_common/install/local_setup.bash"
                eval "$(register-python-argcomplete3 ros2)"
                
                export ROS_DISCOVERY_SERVER=dds:11811
                echo "setting ROS_DISCOVERY_SERVER=${ROS_DISCOVERY_SERVER}"
                echo "running audio capture"
                ros2 run audio_capture audio_capture_node
        depends_on: ['dds']
            
        volumes:
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native                   #unix socket
            - ~/.config/pulse/cookie:/root/.config/pulse/cookie
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        devices:
            - /dev/snd
             

##################################
## DDS service ###################
##################################

    dds:
        build:
            context: .
            dockerfile: foxy_audio.dockerfile

        stdin_open: true     #docker run -i
        tty: true            #docker run -t

        ports:
            - "11811"       #default port for fastdds see https://fast-dds.docs.eprosima.com/en/latest/fastddscli/cli/cli.html#cli-discovery

        environment:
            - DISPLAY
            - XDG_RUNTIME_DIR
            
        command: 
            - /bin/bash
            - -c 
            - |
                echo "Starting DDS. "
                echo "source foxy global setup.bash"
                source "/opt/ros/foxy/setup.bash"
                echo "source "/opt/ros2_ws/src/audio_common/install/local_setup.bash""
                source "/opt/ros2_ws/src/audio_common/install/local_setup.bash"
                eval "$(register-python-argcomplete3 ros2)"
                export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
                echo "Start the discovery server"
                fastdds discovery -i 0

###########################################
## Subscribe from DDS ##
###########################################

    collector-app:
        build: 
            context: .
            dockerfile: foxy_audio.dockerfile
            args:
                XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
                ROS2_WS: /opt/ros2_ws 
                ROS_DISTRO: foxy
            
        stdin_open: true     #docker run -i
        tty: true            #docker run -t
        
        depends_on:
            - dds
            - recorder-app 
               
        environment:
            - DISPLAY
            - XDG_RUNTIME_DIR

        command: 
            - /bin/bash
            - -c 
            - |
                echo "Starting the collection service"
                echo "source foxy global setup.bash"
                source "/opt/ros/foxy/setup.bash"
                echo "source "/opt/ros2_ws/src/audio_common/install/local_setup.bash""
                source "/opt/ros2_ws/src/audio_common/install/local_setup.bash"
                eval "$(register-python-argcomplete3 ros2)"
                
                export ROS_DISCOVERY_SERVER="dds:11811"
                echo "setting ROS_DISCOVERY_SERVER=${ROS_DISCOVERY_SERVER}"
                echo "running audio loop"
                ros2 run audio_play audio_play_node

        
        volumes:
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
            - ~/.config/pulse/cookie:/root/.config/pulse/cookie
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        devices:
            - /dev/snd
        
   
           