services:
    recorder-app:
        build: 
            context: .
            dockerfile: foxy_audio_as_root_1.dockerfile

        stdin_open: true     #docker run -i
        tty: true            #docker run -t
             
##  PulseAudio access with UNIX Socket
##  https://hub.docker.com/r/kyokuheki/vmware-horizon-client  
        
        environment:
            - DISPLAY
            - XDG_RUNTIME_DIR
            - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
        command: echo "I'm using ${DISPLAY} and ${XDG_RUNTIME_DIR} "    
             
        volumes:
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
            - ~/.config/pulse/cookie:/root/.config/pulse/cookie
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        # devices:
        #     - /dev/snd
             

            
volumes:
    xdg_runtime_dir:    
           